version: '3.9'

volumes:
  models:

services:
  alpaca:
    build: .
    volumes:
      - .:/app
      - models:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "7860:7860"